import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '@/styles/Home.module.css'
import Search from '@/components/Search'
import dynamic from 'next/dynamic'
import { useEffect } from 'react'
import GoMachines from '@/components/GoMachines'
